package com.example.madproject.firebase;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;

import androidx.test.ext.junit.runners.AndroidJUnit4;

import com.example.madproject.models.Contract;
import com.google.android.gms.tasks.Tasks;
import com.google.firebase.firestore.DocumentSnapshot;
import com.google.firebase.firestore.QuerySnapshot;

import org.junit.After;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.TimeUnit;

/**
 * Instrumented (live Firestore) tests for {@link ContractManager}. Hits the real
 * "madproject-5c465" Firebase project - see {@link FirebaseTestUtils} for details.
 *
 * Note: ContractManager does not expose a delete method for the "contracts"
 * collection, so teardown here deletes test-created documents directly via
 * {@link FirebaseTestUtils#deleteDocument(String, String)}.
 */
@RunWith(AndroidJUnit4.class)
public class ContractManagerTest {

    private static final String COLLECTION = "contracts";

    private final ContractManager contractManager = ContractManager.getInstance();
    private final List<String> createdIds = new ArrayList<>();

    @BeforeClass
    public static void setUpClass() {
        FirebaseTestUtils.signIn();
    }

    @After
    public void tearDown() throws Exception {
        for (String id : createdIds) {
            FirebaseTestUtils.deleteDocument(COLLECTION, id);
        }
        createdIds.clear();
    }

    private Contract newContract(String id, String jobId) {
        return new Contract(id, jobId, "Test Job", "apitest_client", "apitest_contractor",
                "This is a test contract body generated by an instrumented test.");
    }

    @Test
    public void testCreateAndGetContract_roundTrip() throws Exception {
        String jobId = FirebaseTestUtils.newTestId();
        String id = FirebaseTestUtils.newTestId();
        Contract contract = newContract(id, jobId);

        Tasks.await(contractManager.createContract(contract), FirebaseTestUtils.DEFAULT_TIMEOUT_SECONDS, TimeUnit.SECONDS);
        createdIds.add(id);

        DocumentSnapshot snapshot = Tasks.await(contractManager.getContract(id), FirebaseTestUtils.DEFAULT_TIMEOUT_SECONDS, TimeUnit.SECONDS);
        assertTrue(snapshot.exists());
        Contract fetched = snapshot.toObject(Contract.class);
        assertNotNull(fetched);
        assertEquals(id, fetched.getContractId());
        assertEquals(jobId, fetched.getJobId());
        assertFalse(fetched.isClientEmailSent());
        assertFalse(fetched.isContractorEmailSent());
    }

    @Test
    public void testGetContractsByJob_findsCreatedContract() throws Exception {
        String jobId = FirebaseTestUtils.newTestId();
        String id = FirebaseTestUtils.newTestId();
        Contract contract = newContract(id, jobId);
        Tasks.await(contractManager.createContract(contract), FirebaseTestUtils.DEFAULT_TIMEOUT_SECONDS, TimeUnit.SECONDS);
        createdIds.add(id);

        QuerySnapshot snapshot = Tasks.await(contractManager.getContractsByJob(jobId), FirebaseTestUtils.DEFAULT_TIMEOUT_SECONDS, TimeUnit.SECONDS);
        assertEquals(1, snapshot.size());
        assertEquals(id, snapshot.getDocuments().get(0).getId());
    }

    @Test
    public void testSetPdfUrl_updatesField() throws Exception {
        String jobId = FirebaseTestUtils.newTestId();
        String id = FirebaseTestUtils.newTestId();
        Contract contract = newContract(id, jobId);
        Tasks.await(contractManager.createContract(contract), FirebaseTestUtils.DEFAULT_TIMEOUT_SECONDS, TimeUnit.SECONDS);
        createdIds.add(id);

        Tasks.await(contractManager.setPdfUrl(id, "https://example.com/contract.pdf"),
                FirebaseTestUtils.DEFAULT_TIMEOUT_SECONDS, TimeUnit.SECONDS);

        DocumentSnapshot snapshot = Tasks.await(contractManager.getContract(id), FirebaseTestUtils.DEFAULT_TIMEOUT_SECONDS, TimeUnit.SECONDS);
        Contract fetched = snapshot.toObject(Contract.class);
        assertNotNull(fetched);
        assertEquals("https://example.com/contract.pdf", fetched.getPdfUrl());
    }

    @Test
    public void testMarkEmailSent_forClientAndContractor() throws Exception {
        String jobId = FirebaseTestUtils.newTestId();
        String id = FirebaseTestUtils.newTestId();
        Contract contract = newContract(id, jobId);
        Tasks.await(contractManager.createContract(contract), FirebaseTestUtils.DEFAULT_TIMEOUT_SECONDS, TimeUnit.SECONDS);
        createdIds.add(id);

        Tasks.await(contractManager.markEmailSent(id, true), FirebaseTestUtils.DEFAULT_TIMEOUT_SECONDS, TimeUnit.SECONDS);
        Tasks.await(contractManager.markEmailSent(id, false), FirebaseTestUtils.DEFAULT_TIMEOUT_SECONDS, TimeUnit.SECONDS);

        DocumentSnapshot snapshot = Tasks.await(contractManager.getContract(id), FirebaseTestUtils.DEFAULT_TIMEOUT_SECONDS, TimeUnit.SECONDS);
        Contract fetched = snapshot.toObject(Contract.class);
        assertNotNull(fetched);
        assertTrue(fetched.isClientEmailSent());
        assertTrue(fetched.isContractorEmailSent());
    }

    @Test
    public void testUpdateField_genericFieldUpdate() throws Exception {
        String jobId = FirebaseTestUtils.newTestId();
        String id = FirebaseTestUtils.newTestId();
        Contract contract = newContract(id, jobId);
        Tasks.await(contractManager.createContract(contract), FirebaseTestUtils.DEFAULT_TIMEOUT_SECONDS, TimeUnit.SECONDS);
        createdIds.add(id);

        Tasks.await(contractManager.updateField(id, "contractText", "Updated contract text"),
                FirebaseTestUtils.DEFAULT_TIMEOUT_SECONDS, TimeUnit.SECONDS);

        DocumentSnapshot snapshot = Tasks.await(contractManager.getContract(id), FirebaseTestUtils.DEFAULT_TIMEOUT_SECONDS, TimeUnit.SECONDS);
        Contract fetched = snapshot.toObject(Contract.class);
        assertNotNull(fetched);
        assertEquals("Updated contract text", fetched.getContractText());
    }
}
