package com.example.madproject.firebase;

import android.util.Log;

import com.google.android.gms.tasks.Task;
import com.google.android.gms.tasks.Tasks;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.firestore.FirebaseFirestore;

import java.util.UUID;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.TimeoutException;

/**
 * Shared helpers for the Firebase instrumented test suite under
 * app/src/androidTest/java/com/example/madproject/firebase/.
 *
 * These tests hit the REAL Firebase project ("madproject-5c465") over the network.
 * There is no Firebase emulator configured for this project (deliberate, out of scope
 * here), so every test in this suite is a live integration test against production
 * Firestore. All test-created documents use IDs generated by {@link #newTestId()}
 * (prefixed "apitest_") so they are trivially distinguishable from real user data,
 * and every test file is responsible for deleting whatever it creates in an
 * {@code @After} teardown method.
 *
 * IMPORTANT / MANUAL SETUP REQUIRED:
 * {@link #signIn()} authenticates against Firebase Auth using the constants below.
 * The account apitest@rebuildpak.test does NOT exist yet - it must be created
 * manually by the project owner in the Firebase console (Authentication > Users >
 * Add user) with the email/password below before these tests can sign in
 * successfully. This class cannot create that account itself. Sign-in is treated
 * as best-effort (see {@link #signIn()} javadoc) since it is unknown whether
 * Firestore security rules even require authentication - there is no
 * firestore.rules file checked into this repo.
 */
public final class FirebaseTestUtils {

    private static final String TAG = "FirebaseTestUtils";

    /**
     * Dedicated test account credentials. This account must be created manually in
     * the Firebase console by the project owner - it does not exist automatically.
     */
    public static final String TEST_EMAIL = "apitest@rebuildpak.test";
    public static final String TEST_PASSWORD = "ApiTest123!";

    /** Default timeout (in seconds) used when blocking on Firestore Tasks via Tasks.await(). */
    public static final long DEFAULT_TIMEOUT_SECONDS = 10;

    private FirebaseTestUtils() {
        // static helpers only
    }

    /**
     * Generates a unique, unambiguous test document/entity ID. Always prefixed with
     * "apitest_" so test-created Firestore documents can never collide with real
     * production data and are trivially identifiable/cleanable if a teardown is
     * ever missed.
     */
    public static String newTestId() {
        return "apitest_" + UUID.randomUUID();
    }

    /**
     * Best-effort sign-in against Firebase Auth using the dedicated test account.
     * This is defensive, not a hard requirement: it is unknown whether Firestore
     * security rules for this project require authentication at all (no
     * firestore.rules file exists in this repo to inspect), and the test account
     * may not have been created yet in the Firebase console. If sign-in fails for
     * any reason (account missing, wrong password, network issue, timeout), this
     * method logs a warning and returns quietly rather than throwing, so it never
     * crashes the test run. Tests that strictly require an authenticated user
     * should not rely solely on this - but for this suite, CRUD tests are expected
     * to proceed against Firestore regardless of auth state.
     */
    public static void signIn() {
        try {
            Task<?> task = FirebaseAuth.getInstance()
                    .signInWithEmailAndPassword(TEST_EMAIL, TEST_PASSWORD);
            Tasks.await(task, DEFAULT_TIMEOUT_SECONDS, TimeUnit.SECONDS);
            Log.i(TAG, "Signed in as test account " + TEST_EMAIL);
        } catch (ExecutionException | InterruptedException | TimeoutException e) {
            Log.w(TAG, "Test account sign-in failed (this may be expected if the "
                    + "account has not been created yet in the Firebase console, or "
                    + "if security rules don't require auth). Continuing without "
                    + "authentication. Cause: " + e.getMessage());
        } catch (Exception e) {
            Log.w(TAG, "Unexpected error during test sign-in, continuing without "
                    + "authentication: " + e.getMessage());
        }
    }

    /**
     * Deletes a Firestore document directly, bypassing any Manager class. A couple
     * of Manager classes in this project (ContractManager, PaymentManager) don't
     * expose a delete method for their collection, so tests for those managers use
     * this to clean up test-created documents in teardown.
     */
    public static void deleteDocument(String collection, String documentId) throws Exception {
        Task<Void> task = FirebaseFirestore.getInstance()
                .collection(collection)
                .document(documentId)
                .delete();
        Tasks.await(task, DEFAULT_TIMEOUT_SECONDS, TimeUnit.SECONDS);
    }
}
